### ISSUE TITLE
Does it have apk? 

### ISSUE THREAD

**Issue by robopassion** [pillarpond/facerecognizer#1]

**Comment by pillarpond** [comment]
Please refer to the below link.
[link](https://drive.google.com/file/d/1KlC3HsBkkME1kO8YPNUJqSWtqSd0eqeg/view?usp=sharing)

**Comment by IzzySoft** [comment]
May I recommend to use [tags](https://github.com/pillarpond/face-recognizer-android/releases) and attach the APK there? Many projects do it that way. Drive doesn't work everywhere (and not everyone wants to use it either, keywords "Google" and "Tracking" :wink:)
