### ISSUE TITLE
use another model

### ISSUE THREAD

**Issue by maxteleg** [pillarpond/facerecognizer#2]
Hi, your work is amazing!
   But may I ask how did you generate the facenet.pb file, or just have it copied from the FaceNet project?
Can I use another .pb model I trained instead?

**Comment by pillarpond** [comment]
I had freeze graph without input node "phase_train" using [pre-trained model](https://drive.google.com/open?id=1EXPBSXwTaqrSC0OhUdXNmKSh9qJUQ55-).
Sorry but I don't know exactly what your model is.

**Comment by maxteleg** [comment]
@pillarpond  Thank you for your answer. I have successfully managed to change the FaceNet model to a tensorflow version of [deepinsight face](https://github.com/auroua/InsightFace_TF) with some fine-tuning, and the total inference time seems  to be a little bit longer, but acceptable.
Again, thank you for your great work, which inspired me a lot!
